# Generated by Django 4.1.7 on 2023-03-28 07:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('supervis_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('top_title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('date_post', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архивы',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='Ученая степень')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('reserved_status', models.BooleanField(verbose_name='Статус резервирования')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor', verbose_name='ФИО руководителя')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('supervisor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor', verbose_name='ФИО руководителя')),
                ('topic_title', smart_selects.db_fields.ChainedForeignKey(chained_field='supervisor_name', chained_model_field='supervisor', limit_choices_to={'reserved_status': False}, on_delete=django.db.models.deletion.CASCADE, to='appointment.topic', verbose_name='Наименование темы')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
