# Generated by Django 4.1.7 on 2023-03-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reserved_status', models.BooleanField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.EmailField(max_length=254)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.topic')),
            ],
        ),
    ]
