# Generated by Django 4.1.7 on 2023-03-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.EmailField(max_length=254, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='degree',
            field=models.CharField(max_length=255, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='reserved_status',
            field=models.BooleanField(verbose_name='Статус резервирования'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor', verbose_name='Руководитель'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.student')),
                ('supervisor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor')),
                ('topic_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.topic')),
            ],
        ),
    ]
