# Generated by Django 4.1.7 on 2023-03-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='record',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.student', verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='record',
            name='supervisor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor', verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='record',
            name='topic_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.topic', verbose_name='Наименование темы'),
        ),
    ]
