# Generated by Django 4.1.7 on 2023-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_group_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Группа студента'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
