# Generated by Django 4.1.7 on 2023-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_student_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='student_name',
            field=models.CharField(max_length=255, verbose_name='ФИО студента'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
