# Generated by Django 4.1.7 on 2023-03-16 18:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_topic_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='supervisor_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='topic_title', chained_model_field='topic', on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor'),
        ),
        migrations.AlterField(
            model_name='record',
            name='topic_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.topic'),
        ),
    ]
