# Generated by Django 4.1.7 on 2023-03-16 18:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_record_supervisor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='supervisor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor', verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='record',
            name='topic_title',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='title', chained_model_field='title', on_delete=django.db.models.deletion.CASCADE, to='appointment.topic'),
        ),
    ]
