# Generated by Django 4.1.7 on 2023-03-16 18:50

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_alter_record_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='supervisor',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='title', chained_model_field='name', on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor'),
        ),
    ]
