# Generated by Django 4.1.7 on 2023-03-16 19:00

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_alter_record_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='supervisor_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='student_name', chained_model_field='name', on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.supervisor'),
        ),
    ]
