# Generated by Django 4.1.7 on 2023-03-25 14:16

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0025_alter_record_topic_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='record',
            name='topic_title',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='supervisor_name', chained_model_field='supervisor', limit_choices_to={'reserved_status': False}, on_delete=django.db.models.deletion.CASCADE, to='appointment.topic'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='degree',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ученая степень'),
        ),
    ]
