# Generated by Django 4.1.7 on 2023-03-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0026_alter_supervisor_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['name'], 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
