# Generated by Django 4.1.7 on 2023-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_alter_record_options_alter_supervisor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('supervis_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('top_title', models.CharField(max_length=255, verbose_name='Название темы')),
            ],
        ),
    ]
