# Generated by Django 4.1.7 on 2023-03-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0028_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
