# Generated by Django 4.1.7 on 2023-03-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0030_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Архив', 'verbose_name_plural': 'Архивы'},
        ),
    ]
